/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-17 04:17:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Master;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Master");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    ");

		Master loginMaster = (Master)session.getAttribute("loginMaster");
    
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>Welcome to SECTOR !!</title>\n");
      out.write("\t\t<meta charset=\"utf-8\" />\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"resources/css/main.css\" />\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"resources/js/jquery.min.js\"></script>\n");
      out.write("\t\t<noscript><link rel=\"stylesheet\" href=\"resources/css/noscript.css\" /></noscript>\n");
      out.write("\t\t<!-- <style type=\"text/css\">\n");
      out.write("\t\t\tdiv {\n");
      out.write("\t\t\t\tborder: 1px solid red;\n");
      out.write("\t\t</style>\n");
      out.write("\t\t\t} -->\n");
      out.write("\t</head>\n");
      out.write("\t<body class=\"is-preload\" ><img src=\"images/se.png\" id=\"bg\" alt=\"\"/><audio src=\"images/hello mother f_cker sound effect.mp3\" autoplay></audio>\n");
      out.write("\t\t<!-- onload=\"document.fadeIn();\" -->\n");
      out.write("\t\t<!-- Wrapper -->\n");
      out.write("\t\t\t<div id=\"wrapper\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Header -->\n");
      out.write("\t\t\t\t\t<header id=\"header\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Logo -->\n");
      out.write("\t\t\t\t\t\t\t<a href=\"index.jsp\" class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"symbol\"><img src=\"images/SectorLogo.png\"/></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"title\">Sector</span>\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <a href=\"#main\" class=\"introduce\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>기능 소개</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>  &nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#footer\" class=\"introduce2\">문의 하기</a> -->\n");
      out.write("\t\t\t\t\t\t\t<!-- Nav -->\n");
      out.write("\t\t\t\t\t\t\t\t<nav>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#menu\">Menu</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\n");
 if(loginMaster == null){ // 로그인 안 했을 때 
      out.write("\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Menu -->\n");
      out.write("\t\t\t\t<nav id=\"menu\">\n");
      out.write("\t\t\t\t\t\t<h2 style=\"text-align: center;\">Menu</h2>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"views/login.jsp\">로그인</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#footer\">문의하기</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">공지사항</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t\n");
 } else if(loginMaster.getMasterId().equals("admin")) { 
      out.write("\n");
      out.write("\t<!-- <script type=\"text/javascript\">\n");
      out.write("\t\t$(function(){\n");
      out.write("\t\t\talert(\"관리자 계정으로 로그인 했습니다.\");\n");
      out.write("\t\t});\n");
      out.write("\t</script> -->\n");
      out.write("\t\t\t\t\t<nav id=\"menu\">\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"loginmenu\"><a href=\"views/member/DetailView.jsp\">");
      out.print( loginMaster.getMasterName() );
      out.write(" 님</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"views/member/DetailView.jsp\">관리자 정보</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"views/Admin/memberList.jsp\">회원 관리</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">서비스 신청 현황</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">문의함</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">공지사항 등록</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/Sector/logout\" id=\"logout\" name=\"logout\" onclick=\"logoutm();\">로그아웃</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</nav>\n");
 } else if(loginMaster.getMasterName() != null){ 
      out.write("\n");
      out.write("\t\t\t\t\t<nav id=\"menu\">\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"loginmenu\"><a href=\"views/member/DetailView.jsp\">");
      out.print( loginMaster.getMasterName() );
      out.write(" 님</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"views/member/DetailView.jsp\">내 정보</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#footer\">문의하기</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"views/servicecenter.html\">공지사항</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/Sector/logout\" id=\"logout\" name=\"logout\" onclick=\"logoutm();\">로그아웃</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</nav>\n");
      out.write("\n");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\t\t\tfunction logoutm(){\n");
      out.write("\t\t\t\t\t\t\talert(\"로그아웃 되었습니다.\");\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t<!-- banner -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div id=\"banner\">\n");
      out.write("\t\t\t\t\t\t<img src=\"images/sample1.png\" />\n");
      out.write("\t\t\t\t\t\t<img src=\"images/sample2.png\" />\n");
      out.write("\t\t\t\t\t\t<img src=\"images/sample3.png\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<p></p>\n");
      out.write("\t\t\t\t<!-- Main -->\n");
      out.write("\t\t\t\t\t<div id=\"main\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t\t\t\t<header>\t\n");
      out.write("\t\t\t\t\t\t\t\t<br><br>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"intro\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p id=\"i1\">전자결재, 메일, 게시판, 일정관리, 스케줄러 등</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p id=\"i2\">업무 효율을 높여주는 Sector 그룹웨어, <span class=\"point-txt\">무료</span>로 이용하세요!</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<p/>\n");
      out.write("\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t<section class=\"tiles\" id=\"tiles\">\n");
      out.write("\t\t\t\t\t\t\t\t<article class=\"style1\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"image\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/addressbook.png\" onclick=\"change(1)\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"#tiles\" onclick=\"change(1)\" ;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>주소록</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t\t\t\t<article class=\"style2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"image\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/calander.png\" onclick=\"change(2);\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"#tiles\" onclick=\"change(2)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>캘린더</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t\t\t\t<article class=\"style3\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"image\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/hr.png\" onclick=\"change(3)\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"#tiles\" onclick=\"change(3)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>인사관리</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t\t\t\t<article class=\"style4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"image\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/email.png\" onclick=\"change(4)\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"#tiles\" onclick=\"change(4)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>전자메일</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t\t\t\t<article class=\"style5\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"image\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/board.png\" onclick=\"change(5)\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"#tiles\" onclick=\"change(5)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>게시판</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t\t\t\t<article class=\"style6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"image\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"images/Ap.png\" onclick=\"change(6)\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"#tiles\" onclick=\"change(6)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>전자결재</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</article>\n");
      out.write("\t\t\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- information -->\n");
      out.write("\t\t\t\t<div id=\"info\">\n");
      out.write("\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"infoimg\" id=\"infoimage\" src=\"images/info01.png\"> &nbsp;\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"infotext\" id=\"infotext\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2>주소록</h2><br><h6>비즈니스 필수템</h6><br><h6>보다 효율적인 인맥관리가 가능합니다.</h6>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br><br><br>\n");
      out.write("\t\t\t\t<!-- Footer -->\n");
      out.write("\t\t\t\t\t<footer id=\"footer\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t\t\t\t<section>\n");
      out.write("\t\t\t\t\t\t\t\t<h2>문의 하기</h2>\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\" action=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"fields\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"field half\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" id=\"name\" placeholder=\"이름\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"field half\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" id=\"email\" placeholder=\"이메일\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"field\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<textarea name=\"message\" id=\"message\" placeholder=\"문의 내용\"></textarea>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><input type=\"submit\" value=\"보내기\" class=\"primary\" /></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t\t\t<section>\n");
      out.write("\t\t\t\t\t\t\t\t<h2>SNS</h2>\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"icons\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands style2 fa-github\"><span class=\"label\">GitHub</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands style2 fa-facebook-f\"><span class=\"label\">Facebook</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands style2 fa-instagram\"><span class=\"label\">Instagram</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon solid style2 fa-phone\"><span class=\"label\">Phone</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon solid style2 fa-envelope\"><span class=\"label\">Email</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"copyright\">\n");
      out.write("\t\t\t\t\t\t\t\t<li>&copy; 서울특별시 강남구 테헤란로 남도빌딩 2층 B Class</li><li>Disign by Koogunmo</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</footer>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- Scripts -->\n");
      out.write("\t\t\t<script src=\"resources/js/jquery.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"resources/js/browser.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"resources/js/breakpoints.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"resources/js/util.js\"></script>\n");
      out.write("\t\t\t<script src=\"resources/js/main.js\"></script>\n");
      out.write("\t\t\t<script>\n");
      out.write("\t\t\t\t$(function(){\n");
      out.write("\t\t\t\t\t$('#banner img').hide();\n");
      out.write("\t\t\t\t\t$('#banner img').first().show();\n");
      out.write("\t\t\t\t\tsetInterval(function(){\n");
      out.write("\t\t\t\t\t\t$('#banner').append($('#banner img').first());\n");
      out.write("\t\t\t\t\t\t$('#banner img').last().hide();\n");
      out.write("\t\t\t\t\t\t$('#banner img').first().fadeIn('slow').show(); // 페이드인\n");
      out.write("\t\t\t\t\t}, 5000);\n");
      out.write("\n");
      out.write("\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\tfunction change(input) {\n");
      out.write("\t\t\t\t\tvar num = input;\n");
      out.write("\t\t\t\t\tvar num2 = input;\n");
      out.write("\n");
      out.write("\t\t\t\t\tvar $infotext = document.getElementById('infotext');\n");
      out.write("\n");
      out.write("\t\t\t\t\tif(input < 10) \n");
      out.write("\t\t\t\t\t\tnum = \"0\"+input;\n");
      out.write("\t\t\t\t\tvar imageSrc = \"images/info\"+num+\".png\";\n");
      out.write("\n");
      out.write("\t\t\t\t\tdocument.getElementById('infoimage').src = imageSrc;\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tif(num2==1){\n");
      out.write("\t\t\t\t\t\t$infotext.innerHTML = \"<h2>주소록</h2><br><h6>비즈니스 필수템</h6><br><h6>보다 효율적인 인맥관리가 가능합니다.</h6>\";\n");
      out.write("\t\t\t\t\t}else if(num2==2){\n");
      out.write("\t\t\t\t\t\t$infotext.innerHTML = \"<h2>캘린더</h2><br><h6>우리의 타임키퍼</h6><br><h6>개인적으로 사용하고 싶을만큼 편리합니다.</h6>\";\n");
      out.write("\t\t\t\t\t}else if(num2==3){\n");
      out.write("\t\t\t\t\t\t$infotext.innerHTML = \"<h2>인사관리</h2><br><h6>회사 사랑 직원 사랑</h6><br><h6>직원들은 월급을 주지 않으면 일을 하기 싫어합니다.</h6>\";\n");
      out.write("\t\t\t\t\t}else if(num2==4){\n");
      out.write("\t\t\t\t\t\t$infotext.innerHTML = \"<h2>전자메일</h2><br><h6>스팸, 피싱 메일과의 이별</h6><br><h6>사내 도메인을 사용하여 외부 바이러스 걱정이 없습니다.</h6>\";\n");
      out.write("\t\t\t\t\t}else if(num2==5){\n");
      out.write("\t\t\t\t\t\t$infotext.innerHTML = \"<h2>게시판</h2><br><h6>거의 뭐 클라우드(?)</h6><br><h6>그냥 일반 게시판입니다. 이쁩니다.</h6>\";\n");
      out.write("\t\t\t\t\t}else if(num2==6){\n");
      out.write("\t\t\t\t\t\t$infotext.innerHTML = \"<h2>전자결재</h2><br><h6>기업에는 꼭 필요한 ERP</h6><br><h6>언제까지 결재서류 들고 다니시겠습니까?</h6>\";\n");
      out.write("\t\t\t\t\t}\n");
      out.write("            }\n");
      out.write("\t\t\t$('.tiles').click(function() { \n");
      out.write("\t\t\t\t$('.infoimg').fadeIn('slow', function() { \n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t$('.infotext').fadeIn('slow', function(){\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t</script>\n");
      out.write("\t\t\t<script>\n");
      out.write("\t\t\t\t$(\"body\").hide().fadeIn(1500);\n");
      out.write("\t\t\t</script>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
