/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-16 08:26:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Master;

public final class searchId_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Master");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>IdSearch</title>\n");
      out.write("\t\t<meta charset=\"utf-8\" />\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../../resources/css/search.css\" />\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../../resources/js/jquery.min.js\"></script>\n");
      out.write("\t\t<noscript><link rel=\"stylesheet\" href=\"../../resources/css/noscript.css\" /></noscript>\n");
      out.write("\n");
      out.write("\t\t");

			String result = (String)session.getAttribute("result");
			if(result == null){
				result = "s";
			}
			else if(result.equals("실패")){
		
      out.write("\t\t\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\t$(function(){\n");
      out.write("\t\t\t\t\talert(\"등록된 계정이 없습니다.\");\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t</script>\n");
      out.write("\t\t");

			session.removeAttribute("result");
			} else {
        
      out.write("\n");
      out.write("            <script type=\"text/javascript\">\n");
      out.write("            var result = \"");
      out.print( result );
      out.write("\";\n");
      out.write("                $(function(){\n");
      out.write("                    // window.open(\"http://www.naver.com/\", \"\", \"width=400, height=300\");\n");
      out.write("                    \n");
      out.write("                    alert(\"가입된 정보의 아이디는 '\" + result + \"' 입니다.\");\n");
      out.write("                    location.href=\"./searchPwd.jsp\";\n");
      out.write("                });\n");
      out.write("            </script>\n");
      out.write("        ");

            session.removeAttribute("result");
            }
        
      out.write("\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\tfunction loginname(){\n");
      out.write("\t\t\t\tif($(\"#username\").val() != \"\"){\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"username\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"username\").style.backgroundColor=\"#e9f1ff\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"username\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tfunction loginemail(){\n");
      out.write("\t\t\t\tif($(\"#useremail\").val() != \"\"){\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"useremail\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"useremail\").style.backgroundColor=\"#e9f1ff\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"useremail\").style.transition=\"700ms\"\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("             function phone(){\n");
      out.write("\t\t\t    if($(\"#sphone\").val() != \"\"){\n");
      out.write("                    document.getElementById(\"sphone\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("                    document.getElementById(\"sphone\").style.backgroundColor=\"#e9f1ff\";\n");
      out.write("\t\t\t\t    document.getElementById(\"sphone\").style.transition=\"700ms\"\n");
      out.write("\t\t\t    }\n");
      out.write("\t\t\t}\n");
      out.write("\t\t</script>\n");
      out.write("\n");
      out.write("\t</head>\n");
      out.write("\t<body class=\"is-preload\" onload=\"document.searchfrm.userid.focus();\"><img src=\"../../images/se.png\" id=\"bg\" alt=\"\">\n");
      out.write("\t\t\t<!-- onload=\"document.loginfrm.userid.focus()\" -->\n");
      out.write("\t\t<!-- Wrapper --> \n");
      out.write("\t\t\t<div id=\"wrapper\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Header -->\n");
      out.write("\t\t\t\t\t<header id=\"header\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Logo -->\n");
      out.write("\t\t\t\t\t\t\t<a href=\"../../index.jsp\" class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"symbol\"><img src=\"../../images/SectorLogo.png\"/></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"title\">Sector</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Nav -->\n");
      out.write("\t\t\t\t\t\t\t\t<nav>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#menu\">Menu</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</header>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Menu -->\n");
      out.write("\t\t\t\t\t<nav id=\"menu\">\n");
      out.write("\t\t\t\t\t\t<h2>Menu</h2>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"../../index.jsp\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"../login.jsp\">로그인</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"../../index.jsp#footer\">문의하기</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"../servicecenter.html\">공지사항</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\n");
      out.write("                <!-- login -->\n");
      out.write("                \n");
      out.write("\t\t\t\t\t<div id=\"login\" class=\"login\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"intro\">\n");
      out.write("\t\t\t\t\t\t\t\t<br><br><br>\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"align-center\">아이디 찾기</h2>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<section class=\"loginsec\">\n");
      out.write("\t\t\t\t\t\t\t<form action=\"/Sector/idsearch\" method=\"post\" class=\"searchfrm\" id=\"searchfrm\" name=\"searchfrm\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"loginforminput\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"username\" name=\"username\" minlength=\"2\" required placeholder=\"가입된 이름\" onblur=\"loginname();\"> <br>\n");
      out.write("                                        <input type=\"email\" id=\"useremail\" name=\"useremail\" minlength=\"5\" required placeholder=\"가입된 이메일\" onblur=\"loginemail();\"><br>\n");
      out.write("                                        <input type=\"text\" id=\"sphone\" name=\"sphone\" required placeholder=\"가입된 전화번호\" onblur=\"phone();\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<br><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"btninfo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn\">Search</button>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("                                            <a href=\"./searchPwd.jsp\" id=\"info1\">비밀번호 찾기</a>\n");
      out.write("                                             \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"../login.jsp\" id=\"info2\">로그인</a> \n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</form>\t\t\n");
      out.write("\t\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<!-- Footer -->\n");
      out.write("\t\t\t\t\t<footer id=\"footer\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"copyright\">\n");
      out.write("\t\t\t\t\t\t\t\t<li>&copy; 서울특별시 강남구 테헤란로 남도빌딩 2층 B</li><li>Disign by Koogunmo</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</footer>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- Scripts -->\n");
      out.write("\t\t\t<script src=\"../../resources/js/jquery.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"../../resources/js/browser.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"../../resources/js/breakpoints.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"../../resources/js/util.js\"></script>\n");
      out.write("\t\t\t<script src=\"../../resources/js/main.js\"></script>\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t$(function(){\n");
      out.write("\t\t\t\t$('div#login').focus();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t</script>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
