/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-17 00:38:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class enroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>Enroll</title>\n");
      out.write("\t\t<meta charset=\"utf-8\" />\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../resources/css/enroll.css\" />\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/js/jquery.min.js\"></script>\n");
      out.write("\t\t<noscript><link rel=\"stylesheet\" href=\"../resources/css/noscript.css\" /></noscript>\n");
      out.write("\t\t\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t var checkcnt = 0;\n");
      out.write("\t\n");
      out.write("\t\t var getMail = RegExp(/^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/);\n");
      out.write("\t\t var getCheck= RegExp(/^[a-zA-Z0-9]{4,12}$/);\n");
      out.write("\t\t var getPwd = RegExp(/^(?=.*[a-zA-Z])((?=.*\\d)|(?=.*\\W)).{6,12}$/);\n");
      out.write("\t\t \n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t\t var fmt = RegExp(/^\\d{6}[1234]\\d{6}$/); //형식 설정\n");
      out.write("\t\t//  var buf = new Array(13); //주민등록번호 배열\n");
      out.write("\t\t\tfunction validate() {\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t \n");
      out.write("\t\t\t      //아이디 공백 확인\n");
      out.write("\t\t\t      if($(\"#userid\").val() == \"\"){\n");
      out.write("\t\t\t        alert(\"아이디를 입력하세요.\");\n");
      out.write("\t\t\t        $(\"#userid\").focus();\n");
      out.write("\t\t\t        return false;\n");
      out.write("\t\t\t      }\n");
      out.write("\n");
      out.write("\t\t\t     //이메일 공백 확인\n");
      out.write("\t\t\t      if($(\"#email\").val() == \"\"){\n");
      out.write("\t\t\t        alert(\"이메일을 입력해주세요.\");\n");
      out.write("\t\t\t        $(\"#email\").focus();\n");
      out.write("\t\t\t        return false;\n");
      out.write("\t\t\t\t  }\n");
      out.write("\t\t\t\t  \n");
      out.write("\t\t\t\t  if($(\"#userpwd\").val() == \"\" || $(\"#userpwd2\").val() == \"\"){\n");
      out.write("                    alert(\"비밀번호를 입력해주세요.\");\n");
      out.write("                    $(\"#userpwd\").val(\"\");\n");
      out.write("                    $(\"#userpwd2\").val(\"\");\n");
      out.write("                    $(\"#userpwd\").focus();\n");
      out.write("\t\t\t        return false;\n");
      out.write("\t\t\t\t  }\n");
      out.write("\t\t\t\t  \n");
      out.write("\t\t\t\t  if($(\"#username\").val() == \"\"){\n");
      out.write("\t\t\t        alert(\"이름을 입력해주세요.\");\n");
      out.write("\t\t\t        $(\"#username\").focus();\n");
      out.write("\t\t\t        return false;\n");
      out.write("\t\t\t\t  }\n");
      out.write("\n");
      out.write("\t\t\t\t  if($(\"#phone\").val() == \"\"){\n");
      out.write("\t\t\t        alert(\"전화번호를 입력해주세요.\");\n");
      out.write("\t\t\t        $(\"#phone\").focus();\n");
      out.write("\t\t\t        return false;\n");
      out.write("\t\t\t\t  }\n");
      out.write("\t\t\t\t  \n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t  \n");
      out.write("\n");
      out.write("\t\t\t    //   //주민번호\n");
      out.write("\t\t\t    //   if(($(\"#usernumber1\").val() == \"\") || ($(\"#usernumber2\").val() == \"\")){\n");
      out.write("\t\t\t    //     alert(\"주민등록번호를 입력해주세요.\");\n");
      out.write("\t\t\t    //     $(\"#usernumber1\").focus();\n");
      out.write("\t\t\t    //     return false;\n");
      out.write("\t\t\t    //   }\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t    //   if(check_jumin() == false){\n");
      out.write("\t\t\t    //     return false;\n");
      out.write("\t\t\t    //   } \n");
      out.write("\t\t\t      \n");
      out.write("\t\t\t  \n");
      out.write("\t\t\t\talert(\"회원이 되신걸 축하드립니다!\");\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\treturn true;\n");
      out.write("\t\t\t    // return true;\n");
      out.write("\t\t\t  }\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t  //주민번호 확인 함수\n");
      out.write("\t\t\t//   function check_jumin() {\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t//     var jumins3 = $(\"#usernumber1\").val() + $(\"#usernumber2\").val();\n");
      out.write("\t\t\t//       //주민등록번호 생년월일 전달\n");
      out.write("\t\t\t          \n");
      out.write("\t\t\t//       var fmt = RegExp(/^\\d{6}[1234]\\d{6}$/)  //포멧 설정\n");
      out.write("\t\t\t//       var buf = new Array(13);\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t//       //주민번호 유효성 검사\n");
      out.write("\t\t\t//       if (!fmt.test(jumins3)) {\n");
      out.write("\t\t\t//         alert(\"주민등록번호 형식에 맞게 입력해주세요.\");\n");
      out.write("\t\t\t//         $(\"#usernumber1\").focus();\n");
      out.write("\t\t\t//         return false;\n");
      out.write("\t\t\t//       }\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t//       //주민번호 존재 검사\n");
      out.write("\t\t\t//       for (var i = 0; i < buf.length; i++){\n");
      out.write("\t\t\t//         buf[i] = parseInt(jumins3.charAt(i));\n");
      out.write("\t\t\t//       }\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t//       var multipliers = [2,3,4,5,6,7,8,9,2,3,4,5];// 밑에 더해주는 12자리 숫자들 \n");
      out.write("\t\t\t//       var sum = 0;\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t//       for (var i = 0; i < 12; i++){\n");
      out.write("\t\t\t//       sum += (buf[i] *= multipliers[i]);// 배열끼리12번 돌면서 \n");
      out.write("\t\t\t//     }\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t//     if ((11 - (sum % 11)) % 10 != buf[12]) {\n");
      out.write("\t\t\t//       alert(\"잘못된 주민등록번호 입니다.\");\n");
      out.write("\t\t\t//       $(\"#usernumber1\").focus();\n");
      out.write("\t\t\t//       return false;\n");
      out.write("\t\t\t//     }\n");
      out.write("    \n");
      out.write("\t\t\t//   } \n");
      out.write("\t\t\t  \n");
      out.write("\t\t\t  \n");
      out.write("\t\t\t//   function juminCheck(){\n");
      out.write("\t\t\t// \tdocument.getElementById(\"usernumber1\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t// \tdocument.getElementById(\"usernumber2\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t// \tvar jumins3 = $(\"#usernumber1\").val() + $(\"#usernumber2\").val();\n");
      out.write("\t\t\t//       //주민등록번호 생년월일 전달\n");
      out.write("\t\t\t          \n");
      out.write("\t\t\t//       var fmt = RegExp(/^\\d{6}[1234]\\d{6}$/)  //포멧 설정\n");
      out.write("\t\t\t//       var buf = new Array(13);\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t//       //주민번호 유효성 검사\n");
      out.write("\t\t\t//       if (!fmt.test(jumins3)) {\n");
      out.write("\t\t\t//         alert(\"주민등록번호 형식에 맞게 입력해주세요.\");\n");
      out.write("\t\t\t//         $(\"#usernumber1\").focus();\n");
      out.write("\t\t\t//         return false;\n");
      out.write("\t\t\t//       }\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t//       //주민번호 존재 검사\n");
      out.write("\t\t\t//       for (var i = 0; i < buf.length; i++){\n");
      out.write("\t\t\t//         buf[i] = parseInt(jumins3.charAt(i));\n");
      out.write("\t\t\t//       }\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t//       var multipliers = [2,3,4,5,6,7,8,9,2,3,4,5];// 밑에 더해주는 12자리 숫자들 \n");
      out.write("\t\t\t//       var sum = 0;\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t//       for (var i = 0; i < 12; i++){\n");
      out.write("\t\t\t//       sum += (buf[i] *= multipliers[i]);// 배열끼리12번 돌면서 \n");
      out.write("\t\t\t//     }\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t//     if ((11 - (sum % 11)) % 10 != buf[12] && $(\"#usernumber1\").val() != \"\" && $(\"#usernumber2\").val() != \"\") {\n");
      out.write("\t\t\t//       alert(\"잘못된 주민등록번호 입니다.\");\n");
      out.write("\t\t\t// \t  $(\"#usernumber1\").focus();\n");
      out.write("\t\t\t// \t  $(\"#usernumber2\").val(\"\");\n");
      out.write("\t\t\t// \t  return false;\n");
      out.write("\t\t\t// \t}\n");
      out.write("\t\t\t// \t  var userno =  $(\"#usernumber1\").val() + \"-\" + $(\"#usernumber2\").val();\n");
      out.write("\t\t\t// \t    $.ajax({\n");
      out.write("\t\t\t//             async: false,\n");
      out.write("\t\t\t//             type : 'POST',\n");
      out.write("\t\t\t//             data : {userno: userno},\n");
      out.write("\t\t\t//             url : \"/Sector/jumincheck\",\n");
      out.write("\t\t\t//             // dataType : \"json\", \n");
      out.write("\t\t\t//             // contentType: \"application/json; charset=UTF-8\",\n");
      out.write("\t\t\t//             success : function(data) {\n");
      out.write("\t\t\t//                 if (data > 0) {\n");
      out.write("\t\t\t//                     alert(\"이미 가입된 주민등록번호 입니다.\");\n");
      out.write("\t\t\t//                     $(\"#usernumber1\").focus();\n");
      out.write("\t\t\t//                     $(\"#usernumber2\").val(\"\");\n");
      out.write("\t\t\t// \t\t\t\t\treturn false;\n");
      out.write("\t\t\t//                 }\n");
      out.write("\t\t\t// \t\t\t\telse{\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t// \t\t\t\t}\n");
      out.write("\t\t\t//             },\n");
      out.write("\t\t\t//             error : function(error) {\n");
      out.write("\t\t\t//                 alert(\"error : \" + error);\n");
      out.write("\t\t\t//             }\n");
      out.write("\t\t\t// \t\t});\n");
      out.write("\t\t\t// \t\tdocument.getElementById(\"usernumber1\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("\t\t\t// \t\tdocument.getElementById(\"usernumber2\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("\t\t\t  \n");
      out.write("\t\t\t// }\t\n");
      out.write("\t\t\t  \n");
      out.write("\t\t\t  function emailCheck(){\n");
      out.write("\t\t\t\t// document.getElementById(\"email\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t  var email = $(\"#email\").val();\n");
      out.write("\t\t\t\t  $.ajax({\n");
      out.write("\t\t\t            async: false,\n");
      out.write("\t\t\t            type : 'POST',\n");
      out.write("\t\t\t            data : {email: email},\n");
      out.write("\t\t\t            url : \"/Sector/emailcheck\",\n");
      out.write("\t\t\t            // dataType : \"json\", \n");
      out.write("\t\t\t            // contentType: \"application/json; charset=UTF-8\",\n");
      out.write("\t\t\t            success : function(data) {\n");
      out.write("\t\t\t                if (data > 0) {\n");
      out.write("\t\t\t                    alert(\"이미 가입된 이메일주소 입니다.\");\n");
      out.write("\t\t\t                    $(\"#email\").focus();\n");
      out.write("\t\t\t                    $(\"#email\").val(\"\");\n");
      out.write("\t\t\t\t\t\t\t\t// document.getElementById(\"email\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t\t\t\t\t// document.getElementById(\"email\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t\t\t\t\t// document.getElementById(\"email\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t                }\n");
      out.write("\t\t\t\t\t\t\telse{\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t            },\n");
      out.write("\t\t\t            error : function(error) {\n");
      out.write("\t\t\t                alert(\"error : \" + error);\n");
      out.write("\t\t\t            }\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t\tif(!getMail.test($(\"#email\").val()) && $(\"#email\").val() != \"\"){\n");
      out.write("\t\t\t        alert(\"이메일 형식에 맞게 입력해주세요. (ex : id@gmail.com)\")\n");
      out.write("\t\t\t        $(\"#email\").val(\"\");\n");
      out.write("\t\t\t\t\t$(\"#email\").focus();\n");
      out.write("\t\t\t\t\t// document.getElementById(\"email\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"email\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"email\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\tif($(\"#email\").val() == \"\"){\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"email\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"email\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"email\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"email\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"email\").style.backgroundColor=\"#e9f1ff\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"email\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t  }\n");
      out.write("\n");
      out.write("\t\t\t  \n");
      out.write("\n");
      out.write("\t\t\t  function idcheck(){\n");
      out.write("\t\t\t\tvar userid =  $(\"#userid\").val();\n");
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t// if($(\"#userid\").val() == \"\"){\n");
      out.write("\t\t\t\t// \t\talert(\"아이디를 입력하세요.\");\n");
      out.write("\t\t\t\t//         $(\"#userid\").document.getElementById(\"userid\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t// \t  }\n");
      out.write("\t\t\t\t// else{\n");
      out.write("\t\t\t        $.ajax({\n");
      out.write("\t\t\t            async: false,\n");
      out.write("\t\t\t            type : 'POST',\n");
      out.write("\t\t\t            data : {userid: userid},\n");
      out.write("\t\t\t            url : \"/Sector/logincheck\",\n");
      out.write("\t\t\t            // dataType : \"json\", \n");
      out.write("\t\t\t            // contentType: \"application/json; charset=UTF-8\",\n");
      out.write("\t\t\t            success : function(data) {\n");
      out.write("\t\t\t                if (data > 0) {\n");
      out.write("\t\t\t                    alert(\"이미 사용중인 아이디입니다.\");\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#userid\").val(\"\");\n");
      out.write("\t\t\t                    $(\"#userid\").focus();\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"userid\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"userid\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t\t\t\t\t// document.getElementById(\"userid\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\t\t\t\t// checkcnt == 0;\n");
      out.write("\t\t\t\t\t\t\t\t// return false;\n");
      out.write("\t\t\t                } else if(data <= 0 && $(\"#userid\").val() != \"\"){\n");
      out.write("\t\t\t                    \n");
      out.write("\t\t\t                    // alert(\"사용 가능한 아이디입니다.\");\n");
      out.write("\t\t\t                    // $(\"#userpwd\").focus();\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"userid\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"userid\").style.backgroundColor=\"#e9f1ff\";\n");
      out.write("\t\t\t\t\t\t\t\t// document.getElementById(\"userid\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\t\t\t\t// checkcnt == 1;\n");
      out.write("\t\t\t\t\t\t\t\t// return true;\n");
      out.write("\t\t\t                }\n");
      out.write("\t\t\t            },\n");
      out.write("\t\t\t            error : function(error) {\n");
      out.write("\t\t\t                alert(\"error : \" + error);\n");
      out.write("\t\t\t            }\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\tfunction passCheck(){\n");
      out.write("\t\t\t\t\tif ($(\"#userid\").val()==($(\"#userpwd\").val()) && $(\"#userpwd\").val() != \"\") {\n");
      out.write("\t\t\t\t  alert(\"아이디와 비밀번호를 갖게 만들 수 없습니다.\");\n");
      out.write("\t\t\t\t  $(\"#userpwd\").val(\"\");\n");
      out.write("\t\t\t\t  $(\"#userpwd\").focus();\n");
      out.write("\t\t\t\t//   document.getElementById(\"userpwd\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t//   document.getElementById(\"userpwd\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t  return false;\n");
      out.write("\t\t\t\t  \n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tif(!getPwd.test($(\"#userpwd\").val()) && $(\"#userpwd\").val() != \"\") {\n");
      out.write("\t\t\t      alert(\"비밀번호 형식에 맞게 작성해주세요. (소문자 6~12자 이내 및 숫자 포함)\");\n");
      out.write("\t\t\t      $(\"#userpwd\").val(\"\");\n");
      out.write("\t\t\t\t  $(\"#userpwd\").focus();\n");
      out.write("\t\t\t\t//   document.getElementById(\"userpwd\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t//   document.getElementById(\"userpwd\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t//   document.getElementById(\"userpwd\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t  return false;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tif($(\"#userpwd\").val() == \"\"){\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userpwd\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userpwd\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"userpwd\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userpwd\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userpwd\").style.backgroundColor=\"#e9f1ff\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"userpwd\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\tfunction passCheck2(){\n");
      out.write("\t\t\t\t\tif($(\"#userpwd\").val() != ($(\"#userpwd2\").val()) && $(\"#userpwd2\").val() != \"\"){ \n");
      out.write("\t\t\t      alert(\"비밀번호가 서로 일치하지 않습니다.\");\n");
      out.write("\t\t\t      $(\"#userpwd2\").val(\"\");\n");
      out.write("\t\t\t      $(\"#userpwd2\").focus();\n");
      out.write("\t\t\t\t//   document.getElementById(\"userpwd2\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t//   document.getElementById(\"userpwd2\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t//   document.getElementById(\"userpwd2\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t  return false;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tif($(\"#userpwd2\").val() == \"\"){\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userpwd2\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userpwd2\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"userpwd2\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userpwd2\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userpwd2\").style.backgroundColor=\"#e9f1ff\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"userpwd2\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\tfunction nameCheck(){\n");
      out.write("\n");
      out.write("\t\t\t\t\tvar getName= RegExp(/^[가-힣]{2,}$/);\n");
      out.write("\t\t\t\t\tif (!getName.test($(\"#username\").val()) && $(\"#username\").val() != \"\") {\n");
      out.write("\t\t\t\t\t\talert(\"이름을 올바르게 입력해주세요.\");\n");
      out.write("\t\t\t\t\t\t$(\"#username\").val(\"\");\n");
      out.write("\t\t\t\t\t\t$(\"#username\").focus();\n");
      out.write("\t\t\t\t\t\t// document.getElementById(\"username\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t\t\t// document.getElementById(\"username\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t\t\t// document.getElementById(\"username\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tif($(\"#username\").val() == \"\"){\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"username\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"username\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"username\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"username\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"username\").style.backgroundColor=\"#e9f1ff\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"username\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\tfunction idCheck2(){\n");
      out.write("\t\t\t\t\tvar getCheck= RegExp(/^[a-zA-Z0-9]{4,12}$/);\n");
      out.write("\t\t\t\t\tvar userid =  $(\"#userid\").val();\n");
      out.write("\t\t\t\t\t// alert(userid);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t  if(!getCheck.test($(\"#userid\").val()) && $(\"#userid\").val() != \"\"){\n");
      out.write("\t\t\t\t        alert(\"아이디 형식에 맞게 작성해주세요. (숫자 및 소문자 4~12자 이내)\");\n");
      out.write("\t\t\t\t        $(\"#userid\").val(\"\");\n");
      out.write("\t\t\t\t        $(\"#userid\").focus();\n");
      out.write("\t\t\t\t\t\t// document.getElementById(\"userid\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t\t\t// document.getElementById(\"userid\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t\t\t// document.getElementById(\"userid\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t      }\n");
      out.write("\t\t\t\t\t  if($(\"#userid\").val() == \"\"){\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userid\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userid\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"userid\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t  }\n");
      out.write("\n");
      out.write("\t\t\t\t\t  idcheck();\n");
      out.write("\n");
      out.write("\t\t\t\t\t//  if(idcheck() == false){\n");
      out.write("\n");
      out.write("\t\t\t\t\t// document.getElementById(\"userid\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"userid\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t\t//  }else{\n");
      out.write("\t\t\t\t\t// \tdocument.getElementById(\"userid\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("\t\t\t\t\t// \tdocument.getElementById(\"userid\").style.backgroundColor=\"#e9f1ff\";\n");
      out.write("\t\t\t\t\t//  }\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t// if(idcheckcount == 1){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\tfunction phoneCheck(){\n");
      out.write("\t\t\t\t\tvar getPhone= RegExp(/^010\\d{4}\\d{4}$/);\n");
      out.write("\t\t\t\t\tvar phone =  $(\"#phone\").val();\n");
      out.write("\t\t\t\t\t// alert(userid);\n");
      out.write("\n");
      out.write("\t\t\t\t\t  if(!getPhone.test($(\"#phone\").val()) && $(\"#phone\").val() != \"\"){\n");
      out.write("\t\t\t\t        alert(\"전화번호 형식에 맞게 작성해주세요. (ex : 01012345678)\");\n");
      out.write("\t\t\t\t        $(\"#phone\").val(\"\");\n");
      out.write("\t\t\t\t        $(\"#phone\").focus();\n");
      out.write("\t\t\t\t\t\t// document.getElementById(\"phone\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t\t\t// document.getElementById(\"phone\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t\t\t// document.getElementById(\"phone\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t      }\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t  if($(\"#phone\").val() == \"\"){\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"phone\").style.borderBottom=\"solid 1px #c9c9c9\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"phone\").style.backgroundColor=\"white\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"phone\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"phone\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"phone\").style.backgroundColor=\"#e9f1ff\";\n");
      out.write("\t\t\t\t\t// document.getElementById(\"phone\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t  \n");
      out.write("\t\t</script>\n");
      out.write("\t\t<!-- 중복체크 검사 -->\n");
      out.write("\t\t\n");
      out.write("\t</head>\n");
      out.write("\t<body class=\"is-preload\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- onload=\"document.loginfrm.userid.focus()\" -->\n");
      out.write("\t\t<!-- Wrapper -->\n");
      out.write("\t\t\t<div id=\"wrapper\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- Header -->\n");
      out.write("\t\t\t\t\t<header id=\"header\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Logo -->\n");
      out.write("\t\t\t\t\t\t\t<a href=\"../index.jsp\" class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"symbol\"><img src=\"../images/SectorLogo.png\"/></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"title\">Sector</span>\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Nav -->\n");
      out.write("\t\t\t\t\t\t\t\t<nav>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#menu\">Menu</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</header>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Menu -->\n");
      out.write("\t\t\t\t\t<nav id=\"menu\">\n");
      out.write("\t\t\t\t\t\t<h2>Menu</h2>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"../index.jsp\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"./login.jsp\">로그인</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"../index.jsp#footer\">문의하기</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"./servicecenter.html\">공지사항</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</nav>\n");
      out.write("\n");
      out.write("\t\t\t<!-- Enroll -->\n");
      out.write("\t\t\t<img src=\"../images/se.png\" id=\"bg\" alt=\"\">\n");
      out.write("\t<div class=\"innner enroll\">\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<h2 class=\"align-center\">회원 되기</h2>\n");
      out.write("\t\t\n");
      out.write("\t\t\t<form action=\"/Sector/insert\" method=\"post\" class=\"enrollform\" onsubmit=\"return validate();\"> \n");
      out.write("\t\t\t\t<div class=\"en\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"enroll_input\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"username\" id=\"username\" required placeholder=\"이름\" onblur=\"nameCheck();\"><br>\n");
      out.write("\t\t\t\t\t\t<!-- <div class=\"number\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"usernumber\" id=\"usernumber1\" name=\"usernumber1\" maxlength=\"6\" required placeholder=\"주민번호 앞\">-\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" class=\"usernumber\" id=\"usernumber2\" name=\"usernumber2\" onblur=\"juminCheck();\" maxlength=\"7\" required placeholder=\"주민번호 뒤\"><br><br>\n");
      out.write("\t\t\t\t\t\t</div> -->\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"userid\" id=\"userid\" required placeholder=\"아이디 (4~12자 이내)\" onblur=\"idCheck2();\"> <br>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <button id=\"check\" type=\"button\" onclick=\"idcheck();\">중복체크</button><br> -->\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" class=\"userpwd\" id=\"userpwd\" name=\"userpwd\" required placeholder=\"비밀번호 (6~12자 이내, 숫자 포함)\" onblur=\"passCheck();\"><br>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" class=\"userpwd\" id=\"userpwd2\" required placeholder=\"비밀번호 확인\" onblur=\"passCheck2();\"><br>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"phone\" id=\"phone\" required placeholder=\"전화번호 (' - ' 제외)\" onblur=\"phoneCheck();\"><br>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" id=\"email\" name=\"email\" required placeholder=\"이메일\" onblur=\"emailCheck();\"><br>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"result\">\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\">가입하기</button> &nbsp;&nbsp;\t\n");
      out.write("\t\t\t\t\t\t\t<button type=\"reset\">취소하기</button> <br><br>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"helf\">\n");
      out.write("\t\t\t\t\t\t이미 회원이신가요? &nbsp; <a href=\"./login.jsp\">로그인</a>\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Footer -->\n");
      out.write("\t\t\t\t\t<footer id=\"footer\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"copyright\">\t\n");
      out.write("\t\t\t\t\t\t\t\t<li>&copy; 서울특별시 강남구 테헤란로 남도빌딩 2층 B</li><li>Disign by Koogunmo</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</footer>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- Scripts -->\n");
      out.write("\t\t\t<script src=\"../resources/js/jquery.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"../resources/js/browser.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"../resources/js/breakpoints.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"../resources/js/util.js\"></script>\n");
      out.write("\t\t\t<script src=\"../resources/js/main.js\"></script>\n");
      out.write("\t\t\t<!-- <script type=\"text/javascript\">\n");
      out.write("\t\t\t$(function(){\n");
      out.write("\t\t\t\t$('div.enroll_input').focus();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t</script> -->\n");
      out.write("\t\t\t<!-- <script type=\"text/javascript\">\n");
      out.write("\t\t\t\t$(functino('button#reset').on(){\n");
      out.write("\t\t\t\t\thistory.go(-1);\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t</script> -->\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
