/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-17 06:03:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Master;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Master");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>Login</title>\n");
      out.write("\t\t<meta charset=\"utf-8\" />\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../resources/css/login.css\" />\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../resources/js/jquery.min.js\"></script>\n");
      out.write("\t\t<noscript><link rel=\"stylesheet\" href=\"../resources/css/noscript.css\" /></noscript>\n");
      out.write("\n");
      out.write("\t\t");

			String result = (String)session.getAttribute("result");
			if(result == null){
				result = "s";
			}
			if(result.equals("실패")){
		
      out.write("\t\t\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\t$(function(){\n");
      out.write("\t\t\t\t\talert(\"등록된 계정이 없습니다.\");\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t</script>\n");
      out.write("\t\t");

			session.removeAttribute("result");
			}
		
      out.write(" \n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\tfunction loginid(){\n");
      out.write("\t\t\t\tif($(\"#userid\").val() != \"\"){\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userid\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userid\").style.backgroundColor=\"#e9f1ff\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userid\").style.transition=\"700ms\"\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tfunction loginpwd(){\n");
      out.write("\t\t\t\tif($(\"#userpwd\").val() != \"\"){\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userpwd\").style.borderBottom=\"solid 2px #489CFF\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userpwd\").style.backgroundColor=\"#e9f1ff\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userpwd\").style.transition=\"700ms\"\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t</script>\n");
      out.write("\t<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js\" charset=\"utf-8\"></script>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t</head>\n");
      out.write("\t<body class=\"is-preload\" onload=\"document.loginfrm.userid.focus();\"><img src=\"../images/se.png\" id=\"bg\" alt=\"\">\n");
      out.write("\t\t\t<!-- onload=\"document.loginfrm.userid.focus()\" -->\n");
      out.write("\t\t<!-- Wrapper --> \n");
      out.write("\t\t\t<div id=\"wrapper\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Header -->\n");
      out.write("\t\t\t\t\t<header id=\"header\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Logo -->\n");
      out.write("\t\t\t\t\t\t\t<a href=\"../index.jsp\" class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"symbol\"><img src=\"../images/SectorLogo.png\"/></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"title\">Sector</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Nav -->\n");
      out.write("\t\t\t\t\t\t\t\t<nav>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#menu\">Menu</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</header>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Menu -->\n");
      out.write("\t\t\t\t\t<nav id=\"menu\">\n");
      out.write("\t\t\t\t\t\t<h2>Menu</h2>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"../index.jsp\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"./login.jsp\">로그인</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"../index.jsp#footer\">문의하기</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"./servicecenter.html\">공지사항</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- login -->\n");
      out.write("\t\t\t\t\t<div id=\"login\" class=\"login\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"intro\">\n");
      out.write("\t\t\t\t\t\t\t\t<br><br><br>\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"align-center\">로그인</h2>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<section class=\"loginsec\">\n");
      out.write("\t\t\t\t\t\t\t<form action=\"/Sector/login\" method=\"post\" class=\"loginfrm\" id=\"loginfrm\" name=\"loginfrm\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"loginforminput\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"userid\" name=\"userid\" minlength=\"2\" maxlength=\"12\" required placeholder=\"I D\" onblur=\"loginid();\"> <br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"password\" id=\"userpwd\" name=\"userpwd\" minlength=\"2\" required placeholder=\"PASS\" onblur=\"loginpwd();\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<br><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"btninfo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn\">Login</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a id=\"kakao-login-btn\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<script type='text/javascript'>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t// 나의 키\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  Kakao.init('f2b7c168ce83b990eff490475cbc6acf');\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  // 카카오 로그인 버튼\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  Kakao.Auth.createLoginButton({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcontainer: '#kakao-login-btn',\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess: function(authObj) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  // 로그인 성공시, API를 호출\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  Kakao.API.request({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\turl: '/v1/user/me',\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess: function(res) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t// console.log(res);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t  alert(res.properties.nickname+'님 환영합니다!');\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t  location.href=\"../index.jsp\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t  var email = res.kaccount_email;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t  console.log(email);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t  $.ajax({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tasync: false,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype : 'POST',\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata : {email: email},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : \"/Sector/kakaologin\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}); //ajax\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tfail: function(error) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t  alert(\"실패하였습니다.\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  });\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tfail: function(err) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  alert(JSON.stringify(err));\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  });\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t//]]>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  </script>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <a id=\"naver_id_login\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <script type=\"text/javascript\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar naver_id_login = new naver_id_login(\"koogunmo\", \"http://127.0.0.1:8888/Sector/views/callback.jsp\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar state = naver_id_login.getUniqState();\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tnaver_id_login.setButton(\"green\",3,40);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tnaver_id_login.setDomain(\"http://127.0.0.1:8888/Sector/views/login.jsp\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tnaver_id_login.setState(state);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tnaver_id_login.setPopup();\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tnaver_id_login.init_naver_id_login();\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</script> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <br><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"enroll.jsp\" id=\"info1\">회원 가입 </a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"search.jsp\" id=\"info2\">계정 찾기</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</form>\t\t\n");
      out.write("\t\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<!-- Footer -->\n");
      out.write("\t\t\t\t\t<footer id=\"footer\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"copyright\">\n");
      out.write("\t\t\t\t\t\t\t\t<li>&copy; 서울특별시 강남구 테헤란로 남도빌딩 2층 B</li><li>Disign by Koogunmo</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</footer>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- Scripts -->\n");
      out.write("\t\t\t<script src=\"../resources/js/jquery.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"../resources/js/browser.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"../resources/js/breakpoints.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"../resources/js/util.js\"></script>\n");
      out.write("\t\t\t<script src=\"../resources/js/main.js\"></script>\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t$(function(){\n");
      out.write("\t\t\t\t$('div#login').focus();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t</script>\n");
      out.write("\t\t\t<!-- <script>\n");
      out.write("\t\t\t\t\t$(\"body\").hide().fadeIn(1500);\n");
      out.write("\t\t\t\t</script> -->\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
