/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-17 04:29:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Master;

public final class memberList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Master");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write(' ');

    Master loginMaster = (Master)session.getAttribute("loginMaster");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\t\t\n");
      out.write("\t<title>Member List</title>\n");
      out.write("\t<meta charset=\"utf-8\" />\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../../resources/css/memberlist.css\" />\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../resources/js/jquery.min.js\"></script>\n");
      out.write("\t<noscript><link rel=\"stylesheet\" href=\"../../resources/css/noscript.css\" /></noscript>\t\t\t\n");
      out.write("</head>\n");
      out.write("<body class=\"is-preload\" onload=\"document.searchfrm.userid.focus();\"><img src=\"../../images/se.png\" id=\"bg\" alt=\"\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t<!-- Wrapper --> \n");
      out.write("\t\t\t<div id=\"wrapper\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Header -->\n");
      out.write("\t\t\t\t\t<header id=\"header\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Logo -->\n");
      out.write("\t\t\t\t\t\t\t<a href=\"../../index.jsp\" class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"symbol\"><img src=\"../../images/SectorLogo.png\"/></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"title\">Sector</span>\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Nav -->\n");
      out.write("\t\t\t\t\t\t\t\t<nav>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#menu\">Menu</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</header>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Menu -->\n");
      out.write("\t\t\t\t<nav id=\"menu\">\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li id=\"loginmenu\"><a href=\"views/member/DetailView.jsp\">");
      out.print( loginMaster.getMasterName() );
      out.write(" 님</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"../../index.jsp\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"./DetailView.jsp\">관리자 정보</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"./memberList.jsp\">회원 관리</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">서비스 신청 현황</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">문의함</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">공지사항 등록</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/Sector/logout\" id=\"logout\" name=\"logout\" onclick=\"logoutm();\">로그아웃</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</nav>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- List -->\n");
      out.write("\t\t\t\t<form action=\"\" class=\"inner views\">\n");
      out.write("\t\t\t\t\t\t<br><br>\n");
      out.write("\t\t\t\t\t\t\t<table cellspacing=\"5\" cellpadding=\"0\" class=\"view\">\n");
      out.write("\t\t\t\t\t\t\t\t <tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t <th colspan=\"5\" rowspan=\"2\"><h2>회원 목록</h2></th>\n");
      out.write("\t\t\t\t\t\t\t\t </tr>\n");
      out.write("\t\t\t\t\t\t\t\t <tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th colspan=\"2\"><br><br><br></th>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t <tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t <th>이 름</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t <th>아이디</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t <th>이메일</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t <th>회사명</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t <th>서비스</th>\n");
      out.write("\t\t\t\t\t\t\t\t </tr>\n");
      out.write("\t\t\t\t\t\t\t\t <tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t <th colspan=\"2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <button type=\"button\" onclick=\"location='./update.jsp'\" class=\"btn\">수정하기</button> &nbsp;&nbsp; -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <button type=\"reset\"  onclick=\"location='../../index.jsp'\" class=\"btn\">확인</button> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t\t\t\t </tr>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t<br><br>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<!-- Footer -->\n");
      out.write("\t\t\t\t\t<footer id=\"footer\">\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"copyright\">\n");
      out.write("\t\t\t\t\t\t\t\t<li>&copy; 서울특별시 강남구 테헤란로 남도빌딩 2층 B</li><li>Disign by Koogunmo</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</footer>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- Scripts -->\n");
      out.write("\t\t\t<script src=\"../../resources/js/jquery.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"../../resources/js/browser.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"../../resources/js/breakpoints.min.js\"></script>\n");
      out.write("\t\t\t<script src=\"../../resources/js/util.js\"></script>\n");
      out.write("\t\t\t<script src=\"../../resources/js/main.js\"></script>\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t$(function(){\n");
      out.write("\t\t\t\t$('div#login').focus();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t</script>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
